name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub pandas scikit-learn xgboost mlflow joblib

      - name: Set HF Token
        run: echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

      - name: Run Data Prep and Train
        run: |
          mkdir -p data
          python model_building/prep.py
          python model_building/train.py

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update from workflow" || echo "No changes to commit"
          git push https://huggingface:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/absethi1894/Visit_with_Us main
