name: Tourism Project Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to main

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Prepare Dataset
        run: python model_building/prep.py

  model-training:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow huggingface_hub xgboost scikit-learn joblib

      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &
          sleep 5

      - name: Train Model
        run: python model_building/train.py

  deploy-to-hf:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: python -m pip install --upgrade pip
          
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update from workflow" || echo "No changes to commit"
          git push https://huggingface:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/absethi1894/Visit_with_Us main
