name: Tourism Project Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install xgboost pandas scikit-learn mlflow huggingface_hub

      # Step 4: Run the combined pipeline
      - name: Run ML Pipeline
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python model_building/pipeline.py
